files: 
  include:
    - 'src/assets/styles/**/*.scss'
  # ignore:
  #  - 'src/assets/styles/base/*.scss' 

severity: error

linters:

  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: true
    ignore_unspecified: true

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: single_quotes

  NestingDepth:
    enabled: true
    max_depth: 5
  
  ColorVariable:
    enabled: false

  ColorKeyword:
    enabled: true
